baseURL = "https://vasthav.github.io"
title = "Vasthav's Blog"
theme = "hugo-notepadium"
copyright = "©2019 Vasthav."

languageCode = "en-us"
hasCJKLanguage = false

enableRobotsTXT = true
enableInlineShortcodes = true
enableEmoji = true
paginate = 10
summaryLength = 50

# Enable Disqus
disqusShortname = "vasthav"

# Google Analytics
googleAnalytics = "UA-84213835-1"

staticDir = ["static"]

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = ""
license = ""  # CC License

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

# custom navigation items

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Github"
url = "https://github.com/vasthav"